In [ ]:
import numpy as np
fitness_data=np.array([
    [5000, 200, 6],
    [7000, 250, 7],
    [6500, 230, 6],
    [8000, 300, 8],
    [9000, 320, 7],
    [7500, 270, 6],
    [12000, 400, 5]
])

print("----Explore array----")
print(f"Number of dimension:{fitness_data.ndim}")
print(f"Shape of array:{fitness_data.shape}")
print(f"Total number of elements:{fitness_data.size}")



----Explore array----
Number of dimension:2
Shape of array:(7, 3)
Total number of elements:21


In [ ]:
print("--- Slice the data ---")
steps = fitness_data[:, 0]
calories = fitness_data[:, 1]
sleep = fitness_data[:, 2]

print(f"All step values: {steps}")
print(f"All calorie values: {calories}")
print(f"All sleep values: {sleep}")
print(f"First 3 days:\n{fitness_data[:3, :]}")
print(f"Steps and calories only:\n{fitness_data[:, 0:2]}\n")



--- Slice the data ---
All step values: [ 5000  7000  6500  8000  9000  7500 12000]
All calorie values: [200 250 230 300 320 270 400]
All sleep values: [6 7 6 8 7 6 5]
First 3 days:
[[5000  200    6]
 [7000  250    7]
 [6500  230    6]]
Steps and calories only:
[[ 5000   200]
 [ 7000   250]
 [ 6500   230]
 [ 8000   300]
 [ 9000   320]
 [ 7500   270]
 [12000   400]]



In [ ]:
print("--- Reshape the data ---")
print(f"Steps reshaped to (7,1):\n{steps.reshape(7, 1)}")
print(f"Full dataset reshaped to (3,7):\n{fitness_data.reshape(3, 7)}\n")



--- Reshape the data ---
Steps reshaped to (7,1):
[[ 5000]
 [ 7000]
 [ 6500]
 [ 8000]
 [ 9000]
 [ 7500]
 [12000]]
Full dataset reshaped to (3,7):
[[ 5000   200     6  7000   250     7  6500]
 [  230     6  8000   300     8  9000   320]
 [    7  7500   270     6 12000   400     5]]



In [ ]:
print("---Filter the data ---")
print(f"Days where steps > 8000:\n{fitness_data[fitness_data[:, 0] > 8000]}")
print(f"Days where sleep < 6 hours:\n{fitness_data[fitness_data[:, 2] < 6]}")
print(f"Days where calories > 300:\n{fitness_data[fitness_data[:, 1] > 300]}\n")



---Filter the data ---
Days where steps > 8000:
[[ 9000   320     7]
 [12000   400     5]]
Days where sleep < 6 hours:
[[12000   400     5]]
Days where calories > 300:
[[ 9000   320     7]
 [12000   400     5]]



In [ ]:
print("---Use statistical functions ---")
avg_steps = np.mean(steps)
max_steps = np.max(steps)
min_sleep = np.min(sleep)
std_calories = np.std(calories)
range_steps = np.max(steps) - np.min(steps)

print(f"Average steps: {avg_steps:.2f}")
print(f"Maximum steps: {max_steps}")
print(f"Minimum sleep hours: {min_sleep}")
print(f"Standard deviation of calories: {std_calories:.2f}")
print(f"Range of steps: {range_steps}")

---Use statistical functions ---
Average steps: 7857.14
Maximum steps: 12000
Minimum sleep hours: 5
Standard deviation of calories: 61.28
Range of steps: 7000
